In [1]:
#create a numpy arraay:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# create 0-dimentional array with value 18
import numpy as np
arr=np.array(18)
print(arr)

18


In [3]:
#create a 2-D numpy arraay:
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [4]:
#create a 3-D numpy array with two 2-D numpy arrays:
import numpy as np
arr=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(arr)
# the indices identification is very important in numpy and also the axis identification

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [5]:
# the ndim is used to find the dimensions of the ndarray
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[1,2,3]])
d=np.array([[[1,2,3],[4,5,6],[3,5,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dimensions : ',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions :  5


In [7]:
# get the first emlemnt from the following array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[6]*arr[5])

42


In [9]:
# access the elemnt form the first row and second column
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print('the elemnt from first row and second column is : ',arr[0,1])

the elemnt from first row and second column is :  2


In [10]:
# print the last elemnet from the 2nd dim
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,50]])
print('last element from 2nd dim :',arr[1,-1])

last element from 2nd dim : 50


In [11]:
# print the last elemnet from the last dim
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,50]])
print('last element from 2nd dim :',arr[-1,-1])

last element from 2nd dim : 50


In [12]:
# slice the elements from one index to another
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [13]:
# slice the elements from fourth index to last item in list
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [14]:
# slice from the index 3 from the end to index 1 from the starting
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [15]:
# return every other elemnent from index 1 to index 5:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

[2 4]


In [16]:
# from the second element you need to slice elemnts from index 1 to index 4(not included):
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr[1,1:4])

[2 3 4]


In [17]:
# get the data type of an array object
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)

int64


In [18]:
# get the data type of an array containing strings:
import numpy as np
arr=np.array(['apple','banana','cucumber'])
print(arr.dtype)

<U8


In [19]:
# create  an array with data type string:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [20]:
# change data type from float to integer by using 'i'
import numpy as np
arr=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4 5 6 7 8]
int32


In [21]:
# convertion into boolean
import numpy as np
arr=np.array([1,2,3,0])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True  True  True False]
bool


In [22]:
# print the shape of a 2-D array
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)

(2, 5)


In [23]:
# the outermost dimension will have four arrays , each with 3 elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# convert the 1-D array with 12 elements to 3-D array
# The outermost dimensions has 2 arrays that contains 3 arrays in it
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [25]:
# iterate on the element of the following 1-D array:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
for i in arr:
    print(i*2)

2
4
6
8
10
12
14
16
18


In [26]:
# join two arrays
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2=np.concatenate((arr,arr1))
print(arr2)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [27]:
# join two arrays
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.array([1,2,3,4,5])
arr2=np.concatenate((arr,arr1))
print(arr2)

[1 2 3 4 5 1 2 3 4 5]


In [28]:
# split an array(here the array_split(array,size we want to split the given array))
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2, 3, 4]), array([5, 6, 7])]


In [29]:
# find the indexes where the value is four
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,4,5,4,6,4])
x=np.where(arr==4)
print(x)

(array([ 3,  9, 11, 13]),)


In [41]:
# sort the array:
import numpy as np
arr=np.array([3,2,9,1])
arr1=np.sort(arr)
print(arr1)

[1 2 3 9]


In [42]:
# sort the array:
import numpy as np
arr=np.array([3,2,9,1])
arr1=np.sort(arr)[::-1]
print(arr1)

[9 3 2 1]
